--Скрипт создает в базе таблицы и последовательности необходимы для работы приложения EMPLOYEES_ACCOUNTING
--Создаем таблицы
CREATE TABLE DEPARTMENTS (
    ID_DEPARTMENT INT NOT NULL,
    DEPARTMENT_NAME VARCHAR(50),
    ID_HEAD_OF_DEPARTMENT INT,
    PHONE VARCHAR(80),
    EMAIL VARCHAR(80)
);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT INTEG_10 PRIMARY KEY (ID_DEPARTMENT);


CREATE TABLE EMPLOYEES (
    ID_EMPLOYEE INT NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    ID_POSITION INT,
    ID_DEPARTMENT INT
);

ALTER TABLE EMPLOYEES ADD CONSTRAINT INTEG_12 PRIMARY KEY (ID_EMPLOYEE);


CREATE TABLE POSITIONS (
    ID_POSITION INT NOT NULL,
    POSITION_NAME VARCHAR(50),
    SALARY FLOAT
);

ALTER TABLE POSITIONS ADD CONSTRAINT INTEG_8 PRIMARY KEY (ID_POSITION);

--Создаем последовательности

Create sequence DEPARTMENT_SEQUENCE;

Alter sequence DEPARTMENT_SEQUENCE restart with 23;

Create sequence EMPLOYEE_SEQUENCE;

Alter sequence EMPLOYEE_SEQUENCE restart with 40014;

Create sequence POSITION_SEQUENCE;

Alter sequence POSITION_SEQUENCE restart with 224;

COMMIT;